hparams: !!python/object:argparse.Namespace
  batch_size: 16
  ckpt_path: ./ckpt/epoch=1-step=3412.ckpt
  criterion: mse_loss
  d_inner: 2048
  d_k: 64
  d_model: 512
  d_v: 64
  data_dir: ./AnoTransfer-data/real-world-data/
  data_name: '0'
  drop_prob: 0.1
  embedding_dim: 128
  horizon: 3
  hp_path: ./logs/version_2/hparams.yaml
  learning_rate: 0.005
  local: 3
  n_head: 8
  n_kernels: 32
  n_layers: 1
  n_multiv: 6
  n_negative: 5
  n_positive: 5
  n_random: 5
  num_workers: 8
  only_test: 0
  optimizer_name: adam
  w_kernel: 1
  window: 64
